<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>TCG Inventory</AssemblyName>
    <RootNamespace>TCGInventoryShell</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
